/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecPlus.View;

import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mecPlus.Classes.ArquivoClasse;
import mecPlus.Controller.ArquivoController;
import mecPlus.Controller.MarcasController;
import mecPlus.Controller.VeiculoController;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author bsbru
 */
public class ArquivoAdd extends javax.swing.JFrame {

    public String filePath;
    public String fileName;

    /**
     * Creates new form ClientesAdd
     */
    public ArquivoAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clienteNomeAddLabel = new javax.swing.JLabel();
        descricaoArquivoAdd = new javax.swing.JFormattedTextField();
        clienteAddSave = new javax.swing.JButton();
        arquivoSelecaoAdd = new javax.swing.JButton();
        clienteTelefoneAddLabel4 = new javax.swing.JLabel();
        arquivoSelecionadoAdd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Novo Arquivo");

        clienteNomeAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteNomeAddLabel.setText("Descrição");

        descricaoArquivoAdd.setToolTipText("");
        descricaoArquivoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoArquivoAddActionPerformed(evt);
            }
        });

        clienteAddSave.setText("Salvar");
        clienteAddSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteAddSaveMouseClicked(evt);
            }
        });
        clienteAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteAddSaveActionPerformed(evt);
            }
        });

        arquivoSelecaoAdd.setText("Selecionar Arquivo");
        arquivoSelecaoAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arquivoSelecaoAddMouseClicked(evt);
            }
        });
        arquivoSelecaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoSelecaoAddActionPerformed(evt);
            }
        });

        clienteTelefoneAddLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteTelefoneAddLabel4.setText("Arquivo:");

        arquivoSelecionadoAdd.setToolTipText("");
        arquivoSelecionadoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoSelecionadoAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clienteAddSave)
                .addGap(380, 380, 380))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(clienteTelefoneAddLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(arquivoSelecionadoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(197, 197, 197)
                            .addComponent(arquivoSelecaoAdd)
                            .addGap(130, 130, 130)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(368, 368, 368)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(212, 212, 212)
                            .addComponent(clienteNomeAddLabel)
                            .addGap(18, 18, 18)
                            .addComponent(descricaoArquivoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteNomeAddLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(descricaoArquivoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteTelefoneAddLabel4)
                    .addComponent(arquivoSelecionadoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arquivoSelecaoAdd)
                .addGap(177, 177, 177)
                .addComponent(clienteAddSave)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void descricaoArquivoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoArquivoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoArquivoAddActionPerformed

    private void clienteAddSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteAddSaveActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_clienteAddSaveActionPerformed

    private void arquivoSelecaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoSelecaoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquivoSelecaoAddActionPerformed

    private void arquivoSelecionadoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoSelecionadoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquivoSelecionadoAddActionPerformed

    private void arquivoSelecaoAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arquivoSelecaoAddMouseClicked
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showSaveDialog(null);
        if (i == 1) {
            arquivoSelecionadoAdd.setText("");
        } else {
            File arquivo = file.getSelectedFile();
            arquivoSelecionadoAdd.setText(arquivo.getName());

            this.fileName = arquivo.getName();
            this.filePath = arquivo.getPath();

        }
    }//GEN-LAST:event_arquivoSelecaoAddMouseClicked

    private void clienteAddSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteAddSaveMouseClicked
        // TODO add your handling code here:

        if (descricaoArquivoAdd.getText().isEmpty() || arquivoSelecionadoAdd.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Dados incompletos!");
            return;

        }
        try {

            ArquivoController arquivoController = new ArquivoController();

            Path path = FileSystems.getDefault().getPath("").toAbsolutePath();

            File source = new File(this.filePath);
            File dest = new File(path + "/src/mecPlus/Files/" + this.fileName);

   
            try {
                FileUtils.copyFile(source, dest);
            } catch (IOException e) {
                e.printStackTrace();
            }

            boolean insert = arquivoController.insert(descricaoArquivoAdd.getText(), this.fileName);

            if (insert == false) {
                JOptionPane.showMessageDialog(null, "Erro ao inserir os dados!");
            }

            if (insert == true) {
                JOptionPane.showMessageDialog(null, "Arquivo inserido com sucesso!");
                this.limpaTela(evt);

            }

        } catch (Exception e) {

            return;

        }
    }//GEN-LAST:event_clienteAddSaveMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();

        ArquivoController arquivoController = new ArquivoController();
        ArrayList<ArquivoClasse> carregaArquivos = arquivoController.select();

        Arquivos arquivosTela = new Arquivos(carregaArquivos);
        arquivosTela.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void limpaTela(java.awt.event.MouseEvent evt) {

        descricaoArquivoAdd.setText("");
        arquivoSelecionadoAdd.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArquivoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArquivoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArquivoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArquivoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArquivoAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arquivoSelecaoAdd;
    private javax.swing.JFormattedTextField arquivoSelecionadoAdd;
    private javax.swing.JButton clienteAddSave;
    private javax.swing.JLabel clienteNomeAddLabel;
    private javax.swing.JLabel clienteTelefoneAddLabel4;
    private javax.swing.JFormattedTextField descricaoArquivoAdd;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
