/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecPlus.View;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author bsbru
 */
public class ArquivoAdd extends javax.swing.JFrame {

    /**
     * Creates new form ClientesAdd
     */
    public ArquivoAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteEmailAddLabel1 = new javax.swing.JLabel();
        marcaArquivoAdd = new javax.swing.JFormattedTextField();
        clienteTelefoneAddLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        modeloVeiculoArquivoAdd = new javax.swing.JFormattedTextField();
        clienteNomeAddLabel = new javax.swing.JLabel();
        descricaoArquivoAdd = new javax.swing.JFormattedTextField();
        clienteAddSave = new javax.swing.JButton();
        arquivoSelecaoAdd = new javax.swing.JButton();
        clienteTelefoneAddLabel4 = new javax.swing.JLabel();
        arquivoSelecionadoAdd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clienteEmailAddLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteEmailAddLabel1.setText("Marca Veiculo:");

        marcaArquivoAdd.setToolTipText("");
        marcaArquivoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaArquivoAddActionPerformed(evt);
            }
        });

        clienteTelefoneAddLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteTelefoneAddLabel3.setText("Modelo Veiculo:");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Novo Arquivo");

        modeloVeiculoArquivoAdd.setToolTipText("");
        modeloVeiculoArquivoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloVeiculoArquivoAddActionPerformed(evt);
            }
        });

        clienteNomeAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteNomeAddLabel.setText("Descrição");

        descricaoArquivoAdd.setToolTipText("");
        descricaoArquivoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoArquivoAddActionPerformed(evt);
            }
        });

        clienteAddSave.setText("Salvar");
        clienteAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteAddSaveActionPerformed(evt);
            }
        });

        arquivoSelecaoAdd.setText("Selecionar Arquivo");
        arquivoSelecaoAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arquivoSelecaoAddMouseClicked(evt);
            }
        });
        arquivoSelecaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoSelecaoAddActionPerformed(evt);
            }
        });

        clienteTelefoneAddLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteTelefoneAddLabel4.setText("Arquivo:");

        arquivoSelecionadoAdd.setToolTipText("");
        arquivoSelecionadoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoSelecionadoAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(clienteAddSave))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(clienteTelefoneAddLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(arquivoSelecionadoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(clienteNomeAddLabel)
                                        .addComponent(clienteEmailAddLabel1)
                                        .addComponent(clienteTelefoneAddLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(descricaoArquivoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(marcaArquivoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modeloVeiculoArquivoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(arquivoSelecaoAdd)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(clienteNomeAddLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descricaoArquivoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaArquivoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteEmailAddLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteTelefoneAddLabel3)
                    .addComponent(modeloVeiculoArquivoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteTelefoneAddLabel4)
                    .addComponent(arquivoSelecionadoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arquivoSelecaoAdd)
                .addGap(70, 70, 70)
                .addComponent(clienteAddSave)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void marcaArquivoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaArquivoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaArquivoAddActionPerformed

    private void modeloVeiculoArquivoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloVeiculoArquivoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloVeiculoArquivoAddActionPerformed

    private void descricaoArquivoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoArquivoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoArquivoAddActionPerformed

    private void clienteAddSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteAddSaveActionPerformed
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_clienteAddSaveActionPerformed

    private void arquivoSelecaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoSelecaoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquivoSelecaoAddActionPerformed

    private void arquivoSelecionadoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoSelecionadoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquivoSelecionadoAddActionPerformed

    private void arquivoSelecaoAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arquivoSelecaoAddMouseClicked
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser(); 
          file.setFileSelectionMode(JFileChooser.FILES_ONLY);
          int i= file.showSaveDialog(null);
        if (i==1){
            arquivoSelecionadoAdd.setText("");
        } else {
            File arquivo = file.getSelectedFile();
           arquivoSelecionadoAdd.setText(arquivo.getPath());
        }
    }//GEN-LAST:event_arquivoSelecaoAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArquivoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArquivoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArquivoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArquivoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArquivoAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arquivoSelecaoAdd;
    private javax.swing.JFormattedTextField arquivoSelecionadoAdd;
    private javax.swing.JButton clienteAddSave;
    private javax.swing.JLabel clienteEmailAddLabel1;
    private javax.swing.JLabel clienteNomeAddLabel;
    private javax.swing.JLabel clienteTelefoneAddLabel3;
    private javax.swing.JLabel clienteTelefoneAddLabel4;
    private javax.swing.JFormattedTextField descricaoArquivoAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField marcaArquivoAdd;
    private javax.swing.JFormattedTextField modeloVeiculoArquivoAdd;
    // End of variables declaration//GEN-END:variables
}
