/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecPlus.View;

/**
 *
 * @author bsbru
 */
public class ClientesAdd extends javax.swing.JFrame {

    /**
     * Creates new form ClientesAdd
     */
    public ClientesAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteEmailAddLabel1 = new javax.swing.JLabel();
        clienteEmailAdd = new javax.swing.JFormattedTextField();
        clienteCpfAddLabel2 = new javax.swing.JLabel();
        clienteCpfAdd = new javax.swing.JFormattedTextField();
        clienteTelefoneAddLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clienteTelefoneAdd = new javax.swing.JFormattedTextField();
        clienteEnderecoAddLabel4 = new javax.swing.JLabel();
        clienteNomeAddLabel = new javax.swing.JLabel();
        clienteNomeAdd = new javax.swing.JFormattedTextField();
        clienteAddSave = new javax.swing.JButton();
        clienteEnderecoAdd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clienteEmailAddLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteEmailAddLabel1.setText("Email:");

        clienteEmailAdd.setToolTipText("");
        clienteEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEmailAddActionPerformed(evt);
            }
        });

        clienteCpfAddLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteCpfAddLabel2.setText("CPF/CNPJ:");

        clienteCpfAdd.setToolTipText("");
        clienteCpfAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCpfAddActionPerformed(evt);
            }
        });

        clienteTelefoneAddLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteTelefoneAddLabel3.setText("Telefone:");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Novo Cliente");

        clienteTelefoneAdd.setToolTipText("");
        clienteTelefoneAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTelefoneAddActionPerformed(evt);
            }
        });

        clienteEnderecoAddLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteEnderecoAddLabel4.setText("Endereço:");

        clienteNomeAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteNomeAddLabel.setText("Nome:");

        clienteNomeAdd.setToolTipText("");
        clienteNomeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteNomeAddActionPerformed(evt);
            }
        });

        clienteAddSave.setText("Salvar");
        clienteAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteAddSaveActionPerformed(evt);
            }
        });

        clienteEnderecoAdd.setToolTipText("");
        clienteEnderecoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEnderecoAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(clienteAddSave))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clienteNomeAddLabel)
                                    .addComponent(clienteEmailAddLabel1)
                                    .addComponent(clienteTelefoneAddLabel3)
                                    .addComponent(clienteCpfAddLabel2)
                                    .addComponent(clienteEnderecoAddLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clienteNomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteTelefoneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteCpfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteEnderecoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(clienteNomeAddLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteNomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteEmailAddLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteTelefoneAddLabel3)
                    .addComponent(clienteTelefoneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clienteEnderecoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clienteEnderecoAddLabel4))
                        .addGap(101, 101, 101)
                        .addComponent(clienteAddSave))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clienteCpfAddLabel2)
                        .addComponent(clienteCpfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clienteEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteEmailAddActionPerformed

    private void clienteCpfAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCpfAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteCpfAddActionPerformed

    private void clienteTelefoneAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTelefoneAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTelefoneAddActionPerformed

    private void clienteNomeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNomeAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNomeAddActionPerformed

    private void clienteAddSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteAddSaveActionPerformed
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_clienteAddSaveActionPerformed

    private void clienteEnderecoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEnderecoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteEnderecoAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienteAddSave;
    private javax.swing.JFormattedTextField clienteCpfAdd;
    private javax.swing.JLabel clienteCpfAddLabel2;
    private javax.swing.JFormattedTextField clienteEmailAdd;
    private javax.swing.JLabel clienteEmailAddLabel1;
    private javax.swing.JFormattedTextField clienteEnderecoAdd;
    private javax.swing.JLabel clienteEnderecoAddLabel4;
    private javax.swing.JFormattedTextField clienteNomeAdd;
    private javax.swing.JLabel clienteNomeAddLabel;
    private javax.swing.JFormattedTextField clienteTelefoneAdd;
    private javax.swing.JLabel clienteTelefoneAddLabel3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
