/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecPlus.View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mecPlus.Classes.ClienteClasse;
import mecPlus.Classes.MarcasClasse;
import mecPlus.Controller.ClienteController;
import mecPlus.Controller.MarcasController;

/**
 *
 * @author bsbru
 */
public class Marcas extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    
    public ArrayList<MarcasClasse> marcas;
    
    public Marcas(ArrayList<MarcasClasse> marcas) {
        
        this.dispose();

        initComponents();

        this.marcas = marcas;

        this.preencheTabela();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFornecedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMarcas = new javax.swing.JTable();
        MarcaAddButton = new javax.swing.JButton();
        MarcaButtonEdit = new javax.swing.JButton();
        MarcaButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/marca.png"))); // NOI18N
        jLabel1.setText("Marcas");

        jTableMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Descricao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMarcas.setToolTipText("");
        jTableMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMarcasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMarcas);

        javax.swing.GroupLayout jPanelFornecedoresLayout = new javax.swing.GroupLayout(jPanelFornecedores);
        jPanelFornecedores.setLayout(jPanelFornecedoresLayout);
        jPanelFornecedoresLayout.setHorizontalGroup(
            jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE))
        );
        jPanelFornecedoresLayout.setVerticalGroup(
            jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        MarcaAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        MarcaAddButton.setText("Novo");
        MarcaAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcaAddButtonMouseClicked(evt);
            }
        });

        MarcaButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        MarcaButtonEdit.setText("Editar");
        MarcaButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcaButtonEditMouseClicked(evt);
            }
        });
        MarcaButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaButtonEditActionPerformed(evt);
            }
        });

        MarcaButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/remover.png"))); // NOI18N
        MarcaButtonDelete.setText("Excluir");
        MarcaButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcaButtonDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MarcaAddButton)
                                .addGap(18, 18, 18)
                                .addComponent(MarcaButtonEdit)
                                .addGap(18, 18, 18)
                                .addComponent(MarcaButtonDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanelFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MarcaButtonEdit)
                            .addComponent(MarcaButtonDelete)
                            .addComponent(MarcaAddButton))))
                .addGap(18, 18, 18)
                .addComponent(jPanelFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       public boolean preencheTabela() {
        DefaultTableModel tableModel = (DefaultTableModel) jTableMarcas.getModel();
        tableModel.setRowCount(0);
        marcas.forEach((marca) -> {
            tableModel.addRow(new Object[]{
                marca.getId(),
                marca.getDescricao(),

            });

        });
        jTableMarcas.setModel(tableModel);

        return true;
    }
    private void jTableMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMarcasMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableMarcasMouseClicked

    private void MarcaAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaAddButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        MarcasAdd marcasAddTela =  new MarcasAdd();
        marcasAddTela.setVisible(true);
       
    }//GEN-LAST:event_MarcaAddButtonMouseClicked

    private void MarcaButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaButtonEditMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        
                  if (jTableMarcas.getSelectedRow() < 0) {
            return;

        }

        Integer id = (Integer) jTableMarcas.getModel().getValueAt(jTableMarcas.getSelectedRow(), 0);
        String descricao = (String) jTableMarcas.getModel().getValueAt(jTableMarcas.getSelectedRow(), 1);
        
        MarcasClasse marca = new MarcasClasse();
        
        marca.setDescricao(descricao);
        marca.setId(id);
        
        MarcasEdit marcasEditTela =  new MarcasEdit(marca);
        marcasEditTela.setVisible(true);


    }//GEN-LAST:event_MarcaButtonEditMouseClicked

    private void MarcaButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaButtonEditActionPerformed

    private void MarcaButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaButtonDeleteMouseClicked
        // TODO add your handling code here:
       if (jTableMarcas.getSelectedRow() < 0) {
            return;

        }

        Integer id = (Integer) jTableMarcas.getModel().getValueAt(jTableMarcas.getSelectedRow(), 0);

        MarcasClasse marca = new MarcasClasse();
        marca.setId(id);
        
   int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Você realmente deseja excluir o item selecionado?", "Confirmação", dialogButton);
        
        
           if (dialogResult == 0) {
               MarcasController marcaController = new MarcasController();
            boolean remove = marcaController.remove(marca);

            if (remove == true) {
                JOptionPane.showMessageDialog(null, "Item removido com sucesso!");
                this.dispose();
                this.carregaTela();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao remover o item!");
            }

        } else {

        }
        

    }//GEN-LAST:event_MarcaButtonDeleteMouseClicked

            public void carregaTela() {
        MarcasController  marcaController = new MarcasController();
        ArrayList<MarcasClasse> carregaMarcas = marcaController.select();
        
        Marcas marcasTela =  new Marcas(carregaMarcas);
        marcasTela.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MarcaAddButton;
    private javax.swing.JButton MarcaButtonDelete;
    private javax.swing.JButton MarcaButtonEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFornecedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMarcas;
    // End of variables declaration//GEN-END:variables
}
