/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecPlus.View;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mecPlus.Classes.ClienteClasse;
import mecPlus.Classes.ModelosClasse;
import mecPlus.Classes.VeiculoClasse;
import mecPlus.Controller.ModelosController;
import mecPlus.Controller.VeiculoController;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.draw.DottedLineSeparator;

import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;

/**
 *
 * @author bsbru
 */
public class Veiculos extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public ArrayList<VeiculoClasse> veiculos;

    public Veiculos(ArrayList<VeiculoClasse> veiculos) {

        this.dispose();

        initComponents();
        
        this.veiculos = veiculos;

        this.preencheTabela();

    }

    public boolean preencheTabela() {
        DefaultTableModel tableModel = (DefaultTableModel) jTableVeiculos.getModel();
        tableModel.setRowCount(0);
        veiculos.forEach((veiculo) -> {

            tableModel.addRow(new Object[]{
                veiculo.getId(),
                veiculo.getMarcaDescricao(),
                veiculo.getModeloDescricao(),
                veiculo.getAno(),
                veiculo.getPlaca(),
                veiculo.getClienteNome()

            });
            

        });
        jTableVeiculos.setModel(tableModel);

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFornecedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        VeiculosButtonEdit = new javax.swing.JButton();
        VeiculosButtonDelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/moto.png"))); // NOI18N
        jLabel1.setText("Veiculos");

        jTableVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Marca", "Modelo", "Ano", "Placa", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeiculos.setToolTipText("");
        jTableVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVeiculos);

        javax.swing.GroupLayout jPanelFornecedoresLayout = new javax.swing.GroupLayout(jPanelFornecedores);
        jPanelFornecedores.setLayout(jPanelFornecedoresLayout);
        jPanelFornecedoresLayout.setHorizontalGroup(
            jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE))
        );
        jPanelFornecedoresLayout.setVerticalGroup(
            jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jButton1.setText("Novo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        VeiculosButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        VeiculosButtonEdit.setText("Editar");
        VeiculosButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VeiculosButtonEditMouseClicked(evt);
            }
        });
        VeiculosButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeiculosButtonEditActionPerformed(evt);
            }
        });

        VeiculosButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/remover.png"))); // NOI18N
        VeiculosButtonDelete.setText("Excluir");
        VeiculosButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VeiculosButtonDeleteMouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/reports.png"))); // NOI18N
        jButton2.setText("Gerar relatório");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(VeiculosButtonEdit)
                                .addGap(18, 18, 18)
                                .addComponent(VeiculosButtonDelete))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanelFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(VeiculosButtonEdit)
                                    .addComponent(VeiculosButtonDelete)
                                    .addComponent(jButton1)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableVeiculosMouseClicked

        public void geraRelatorio() {
        

        Date dataName = new Date();
        String dataFormatadaFileName = new SimpleDateFormat("dd_MM_YY_HHmmss").format(dataName);
        
        Path path = FileSystems.getDefault().getPath("").toAbsolutePath();
        
        String fileName = "veiculos"+dataFormatadaFileName+".pdf";
        
        String dest = path+"/src/reports/"+fileName;
        
        File file = new File(dest);
        file.getParentFile().mkdirs();

        try {
            
        Date data = new Date();
        String dataFormatada = new SimpleDateFormat("dd-MM-YYYY HH:mm:ss").format(data);

            Document document = new Document() ;
            PdfWriter.getInstance(document, new FileOutputStream(dest));
            document.open();

             int totalItems = this.veiculos.size();
                
//            String dataString = data.toString();
            Chunk linebreak = new Chunk(new DottedLineSeparator());

 
            Font f=new Font(Font.FontFamily.COURIER,30.0f,Font.BOLD,BaseColor.BLACK);
            Paragraph tittle = new Paragraph("Relatório Veículos",f);
            tittle.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(tittle); 
            document.add(linebreak);  
  
     
            document.add(new Paragraph("Gerado em " + dataFormatada));
            document.add(linebreak);
            
             document.add(new Paragraph("Total de items: " + totalItems));
            document.add(linebreak);
 
//            document.add(new Paragraph("Periodo:"));
//            document.add(linebreak);
            
            
            float columnWidth[] = {7, 32, 32, 27, 25};
            PdfPTable table = new PdfPTable(columnWidth);
            table.setWidthPercentage(100);

            table.addCell("ID");
            table.addCell("Marca");
            table.addCell("Modelo");
            table.addCell("ANO");
            table.addCell("Placa");
            

            for (VeiculoClasse element : this.veiculos) {

                table.addCell(element.getId().toString());
                table.addCell(element.getMarcaDescricao());
                table.addCell(element.getModeloDescricao());
                table.addCell(element.getAno());
                table.addCell(element.getPlaca());

            }

            document.add(table);
            document.close();
            
           File myFile = new File(dest);
           Desktop.getDesktop().open(myFile);

        } catch (DocumentException de) {
            System.err.println(de.getMessage());
        } catch (FileNotFoundException e) {
        }
        catch(IOException e){
        }
    }
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.dispose();
     VeiculoClasse veiculos = new VeiculoClasse();
        VeiculosAdd veiculosAddTela = new VeiculosAdd(veiculos);
        veiculosAddTela.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void VeiculosButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VeiculosButtonEditMouseClicked
        // TODO add your handling code here:
        
         if (jTableVeiculos.getSelectedRow() < 0) {
            return;

        }

        Integer id = (Integer) jTableVeiculos.getModel().getValueAt(jTableVeiculos.getSelectedRow(), 0);
        String marca = (String) jTableVeiculos.getModel().getValueAt(jTableVeiculos.getSelectedRow(), 1);
        String modelo = (String) jTableVeiculos.getModel().getValueAt(jTableVeiculos.getSelectedRow(), 2);
        String ano = (String) jTableVeiculos.getModel().getValueAt(jTableVeiculos.getSelectedRow(), 3);
        String placa = (String) jTableVeiculos.getModel().getValueAt(jTableVeiculos.getSelectedRow(), 4);
        String cliente = (String) jTableVeiculos.getModel().getValueAt(jTableVeiculos.getSelectedRow(), 5);
       
        VeiculoClasse veiculo = new VeiculoClasse();
        
        veiculo.setId(id);
        veiculo.setMarcaDescricao(marca);
        veiculo.setModeloDescricao(modelo);
        veiculo.setAno(ano);
        veiculo.setPlaca(placa);
        veiculo.setClienteNome(cliente);
   
        this.dispose();
        
        VeiculosEdit veiculosEditTela = new VeiculosEdit(veiculo);
        veiculosEditTela.setVisible(true);


    }//GEN-LAST:event_VeiculosButtonEditMouseClicked

    private void VeiculosButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeiculosButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VeiculosButtonEditActionPerformed

    private void VeiculosButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VeiculosButtonDeleteMouseClicked
        // TODO add your handling code here:
        if (jTableVeiculos.getSelectedRow() < 0) {
            return;

        }

        Integer id = (Integer) jTableVeiculos.getModel().getValueAt(jTableVeiculos.getSelectedRow(), 0);

        VeiculoClasse veiculo = new VeiculoClasse();
        veiculo.setId(id);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Você realmente deseja excluir o item selecionado?", "Confirmação", dialogButton);

        if (dialogResult == 0) {
            VeiculoController veiculoController = new VeiculoController();
            boolean remove = veiculoController.remove(veiculo);

            if (remove == true) {
                JOptionPane.showMessageDialog(null, "Item removido com sucesso!");
                this.dispose();
                this.carregaTela();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao remover o item!");
            }

        } else {

        }

    }//GEN-LAST:event_VeiculosButtonDeleteMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        this.geraRelatorio();
    }//GEN-LAST:event_jButton2MouseClicked

    public void carregaTela() {
        VeiculoController veiculoController = new VeiculoController();
        ArrayList<VeiculoClasse> carregaVeiculos = veiculoController.select();

        Veiculos veiculosTela = new Veiculos(carregaVeiculos);
        veiculosTela.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VeiculosButtonDelete;
    private javax.swing.JButton VeiculosButtonEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFornecedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeiculos;
    // End of variables declaration//GEN-END:variables
}
