/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecPlus.View;

/**
 *
 * @author bsbru
 */
public class VeiculosEdit extends javax.swing.JFrame {

    /**
     * Creates new form ClienteEdit
     */
    public VeiculosEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteTelefoneTelefoneLabel = new javax.swing.JLabel();
        PlacaVeiculoEdit = new javax.swing.JFormattedTextField();
        clienteEnderecoEdit = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        clienteCpfEditLabel = new javax.swing.JLabel();
        nomeEditLabel = new javax.swing.JLabel();
        AnoVeiculoEdit = new javax.swing.JFormattedTextField();
        veiculoMarcaEdit = new javax.swing.JFormattedTextField();
        cepEditLabel = new javax.swing.JLabel();
        clienteEnderecoEditLabel = new javax.swing.JLabel();
        ModeloVeiculoEdit = new javax.swing.JFormattedTextField();
        clienteEditSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clienteTelefoneTelefoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteTelefoneTelefoneLabel.setText("Placa");

        PlacaVeiculoEdit.setToolTipText("");
        PlacaVeiculoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaVeiculoEditActionPerformed(evt);
            }
        });

        clienteEnderecoEdit.setToolTipText("");
        clienteEnderecoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEnderecoEditActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar Veiculo");

        clienteCpfEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteCpfEditLabel.setText("Ano:");

        nomeEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomeEditLabel.setText("Marca:");

        AnoVeiculoEdit.setToolTipText("");
        AnoVeiculoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoVeiculoEditActionPerformed(evt);
            }
        });

        veiculoMarcaEdit.setToolTipText("");
        veiculoMarcaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoMarcaEditActionPerformed(evt);
            }
        });

        cepEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cepEditLabel.setText("Modelo:");

        clienteEnderecoEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteEnderecoEditLabel.setText("Cliente:");

        ModeloVeiculoEdit.setToolTipText("");
        ModeloVeiculoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloVeiculoEditActionPerformed(evt);
            }
        });

        clienteEditSave.setText("Salvar");
        clienteEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEditSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(veiculoMarcaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ModeloVeiculoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PlacaVeiculoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AnoVeiculoEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(clienteEnderecoEditLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(clienteEnderecoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeEditLabel)
                            .addComponent(clienteTelefoneTelefoneLabel)
                            .addComponent(clienteCpfEditLabel)
                            .addComponent(cepEditLabel))
                        .addGap(366, 366, 366)))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clienteEditSave)
                        .addGap(336, 336, 336))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEditLabel)
                    .addComponent(veiculoMarcaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeloVeiculoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepEditLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlacaVeiculoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteTelefoneTelefoneLabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnoVeiculoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteCpfEditLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteEnderecoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteEnderecoEditLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(clienteEditSave)
                .addGap(91, 91, 91))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlacaVeiculoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaVeiculoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaVeiculoEditActionPerformed

    private void clienteEnderecoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEnderecoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteEnderecoEditActionPerformed

    private void AnoVeiculoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoVeiculoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoVeiculoEditActionPerformed

    private void veiculoMarcaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoMarcaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoMarcaEditActionPerformed

    private void ModeloVeiculoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloVeiculoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloVeiculoEditActionPerformed

    private void clienteEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEditSaveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_clienteEditSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiculosEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField AnoVeiculoEdit;
    private javax.swing.JFormattedTextField ModeloVeiculoEdit;
    private javax.swing.JFormattedTextField PlacaVeiculoEdit;
    private javax.swing.JLabel cepEditLabel;
    private javax.swing.JLabel clienteCpfEditLabel;
    private javax.swing.JButton clienteEditSave;
    private javax.swing.JFormattedTextField clienteEnderecoEdit;
    private javax.swing.JLabel clienteEnderecoEditLabel;
    private javax.swing.JLabel clienteTelefoneTelefoneLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeEditLabel;
    private javax.swing.JFormattedTextField veiculoMarcaEdit;
    // End of variables declaration//GEN-END:variables
}
